resource "google_compute_backend_service" "gkemcs_default_404" {
  connection_draining_timeout_sec = 0
  description                     = "Default BackendService generated by GKE MCS"
  health_checks                   = ["https://www.googleapis.com/compute/v1/projects/qwiklabs-gcp-01-2e74891f7230/global/healthChecks/gkemcs-default-404"]
  load_balancing_scheme           = "INTERNAL_SELF_MANAGED"
  name                            = "gkemcs-default-404"
  port_name                       = "http"
  project                         = "qwiklabs-gcp-01-2e74891f7230"
  protocol                        = "HTTP"
  session_affinity                = "NONE"
  timeout_sec                     = 30
}
# terraform import google_compute_backend_service.gkemcs_default_404 projects/qwiklabs-gcp-01-2e74891f7230/global/backendServices/gkemcs-default-404
